[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "alma"
version = "2.0.2"
description = "Python packages for making requests to the Alma API"
requires-python = ">=3.7"
license = "MIT"
authors = [
  {name = "Gustav Lindqvist", email = "gustav.lindqvist@ju.se"},
]
urls = {Homepage = "https://github.com/JonkopingUniversityLibrary/alma-python-packages"}
dependencies = [
  "httplib2",
  "xmljson",
]

[tool.setuptools]
packages = [
    "alma.analytics_parser",
    "alma.api",
    "alma.marc"
]
